sonar.projectKey=lduchosal_jeff
sonar.organization=lduchosal

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.version=3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=interrogate_badge.svg,htmlcov/**,dist/**,build/**,**/__pycache__/**
sonar.coverage.exclusions=tests/**,src/jeff/__main__.py
